// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkampkccsdiebvkcfuby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYW1wa2Njc2RpZWJ2a2NmdWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NDAxMTYsImV4cCI6MjA2MjMxNjExNn0.LX_uhF0JFDJ4xKriJ4Z8ip753DhTwKJA7lD-uLvlXAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);